<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Flavio\CatFact\ViewModel\CatFact $vm */
$vm = $block->getData('cat_fact_vm');
$catFactData = $vm->getCatFact();

$jsLayout = json_decode($block->getJsLayout(), true);
?>

<div id="cat-fact-banner" data-bind="scope: 'cat-fact-banner'">
    <strong>Cat Fact😺</strong><span><?= $catFactData ?></span>
</div>

<script type="text/x-magento-init">
    {
        "#cat-fact-banner": {
            "Magento_Ui/js/core/app": <?= json_encode($jsLayout) ?>
    }
}
</script>
