<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Flavio\Bookmarks\ViewModel\Bookmark $vm */
$vm = $block->getData('bookmark_vm');
$configValue = $block->getConfigValue('bookmarks_for_customers/general/enable');
$bookmarkList = $vm->getList();
$isConfigParameterOn = $vm->isCustomerBookmarksOn();
?>

<div id="bookmark-grid" data-bind="scope: 'bookmark-grid'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "#bookmark-grid": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
    }
}
</script>
