<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Flavio\Bookmarks\ViewModel\Bookmark $vm */
$vm = $block->getData('bookmark_vm');
$configValue = $block->getConfigValue('bookmarks_for_customers/general/enable');
$bookmarkList = $vm->getList();
$isConfigParameterOn = $vm->isCustomerBookmarksOn();
?>

<!--<span>bookmarks_for_customers/general/enable --><?php //= $vm->isCustomerBookmarksOn(); ?><!--</span>-->

<?php if (empty($bookmarkList)): ?>
    <div class="message info empty">
        <span><?= $escaper->escapeHtml(__('You have no bookmarks yet.')) ?></span>
    </div>
<?php else: ?>
    <table>
        <tbody>
        <?php foreach ($bookmarkList as $bookmark): ?>
            <tr>
                <td><?= $bookmark->getData('page_title') ?></td>
                <td><a href="<?= $bookmark->getData('url') ?>"><?= $bookmark->getData('url') ?></a></td>
                <td><div class="bookmark-icons delete"><span>delete</span></div></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif; ?>
